version: '2'

networks:
  proxy-tier:
    external: true
  back:
    driver: bridge

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - back

  app:
    image: nextcloud:fpm
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    networks:
      - back

  web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    links:
      - app
    volumes:
      - ./nginx.ssl.conf:/etc/nginx/nginx.conf:ro,Z
      - ./ssl:/etc/ssl:ro,Z
    volumes_from:
      - app
    restart: always
    networks:
      - back
      - proxy-tier
